@CoffeShop.Host_HostAddress = http://localhost:5059

GET {{CoffeShop.Host_HostAddress}}/healthz
Accept: application/json

###

GET {{CoffeShop.Host_HostAddress}}/api/Coffees/GetAll
Accept: application/json

###

GET {{CoffeShop.Host_HostAddress}}/api/Customer/GetAllCustomers
Accept: application/json

###
