<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CoffeShop.DL\CoffeShop.DL.csproj" />
		<InternalsVisibleTo Include="CoffeShop.Tests" />
	</ItemGroup>

</Project>
