<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CoffeShop.DL\CoffeShop.DL.csproj" />
		<InternalsVisibleTo Include="CoffeShop.Tests" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Confluent.Kafka" Version="2.14.0" />
	  <PackageReference Include="MessagePack" Version="3.1.4" />
	</ItemGroup>

</Project>
